name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install sqlite3
      run: apt install sqlite3 libsqlite3-dev
    - name: Setup
      run: cargo update
    - name: Build
      run: cargo build --verbose
